language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "chavaillaz"
    token:
      secure: "FX69OXPWHOYNShq8did1U3EUPYzy9D6zM/pmfUyy2CpnkcWyeIVjmeJLHJ2MrJnxpbfmj/gt4TpG9IYeEv0KGM22xdOIlue3tDOc49FhRKVxjRzMLuWF1ejcYls8t4VGqJktqld/+JeCKhufEiXz4xIc6fyMx3vWOjZHQdjeveM9y2tuhs0k1HUj7E/iGr+uSFZe7+Jz4d115rusa3OsSInAlKWfCoyiC9MrRUDDz8Ze6HksGo/5Raz5KbAfgTVNYba0W6SyKWUGX15zr84mu3fS6u6cFIXMKhXYfQtUqxqGdzEF8t382iM6+J/5Pw3JWGxdy84fT7SFe6XtFxZkYHMLZVY+SrjnSoTU0Mbi0+p3xANW6sdHHvyjyUaJLcHkB4+Bu2jIF5Kr4FRqhKQxC1Ivow7PEIj3zEZKX9N2ZNWUWJ5SF25y7+kLU3ar3xIOLQ+ohMsppnr7sQ2BenU02iypRd5medsGFpOJJwjP1/M80LDVp5AaAyjXk+MHPVDDPGhVshuDkXjHfSzfE8PU+NofmwCT5SE+tlMthX7kdVd57o/J+xT74aOjH26vGZpV/n9rHy/fvhLsdq7uixQ3Q5aj4Z8Pg6JVm2ipH2i8/qGEIdUo9AIDt6X0NYzwGwWSqQJrCOHj67ODW+gCrAzGxAbAzGUyS19jR9BQUmrtLH0="

jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
